trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: prodGatsby

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  env:
    GATSBY_ENV: $(GATSBY_ENV)
  displayName: 'npm build'